---
- name: Check pcs auth status (quorum)
  command:
    cmd: >
      pcs status pcsd --
      {% for node in groups.quorum_node %}
        {{ hostvars[node].ha_cluster.node_name | quote }}
      {% endfor %}
  register: __ha_cluster_pcs_auth_quorum_status
  check_mode: no
  # rc == 0 means all nodes are authenticated
  # rc == 2 means not all nodes are authenticated
  # any other rc means an error
  changed_when: __ha_cluster_pcs_auth_quorum_status.rc == 2
  failed_when:
    - __ha_cluster_pcs_auth_status.rc != 0
    - __ha_cluster_pcs_auth_status.rc != 2

- name: Run pcs auth and add quorum device to cluster
  include_tasks: pcs-auth-{{ __ha_cluster_pcs_provider }}-quorum.yml
  # Include the tasks for nodes which can not talk to other nodes due to
  # missing pcs auth tokens. The pcs-auth-*.yml contains "run_once: yes" as
  # running the auth on one node is sufficient (auth tokens are distributed by
  # pcs automatically). By appling "when" here and "run_once" in the included
  # task, it is achieved that the pcs auth command is run once on one of the
  # nodes which lack pcs auth tokens.
  when: not ansible_check_mode and __ha_cluster_pcs_auth_quorum_status.rc == 2
  register: pcs_auth

- name: Add quorum device to cluster
  command:
    cmd: >
      pcs quorum device add model net algorithm=ffsplit host={% for node in groups.quorum_node %}{{ hostvars[node].ha_cluster.node_name | quote }}{% endfor %}
  when: pcs_auth.skipped
  ignore_errors: true

- debug:
    var: pcs_auth  

